"""Attribution / license NOTICE for the foundation track.

Branding the assistant as Darknode is fine. Removing the upstream license
attribution is not -- the base model and datasets carry notice requirements we
must keep. This module is the single source of truth for that NOTICE and can
regenerate the repo-root NOTICE file.

Verify exact license terms against each upstream source before distribution;
the strings below are a compliance starting point, not legal advice.
"""
from __future__ import annotations

from pathlib import Path

COMPONENTS = [
    {
        "name": "WhiteRabbitNeo-13B-v1",
        "role": "base model (default)",
        "source": "https://huggingface.co/WhiteRabbitNeo/WhiteRabbitNeo-13B-v1",
        "license": "WhiteRabbitNeo usage restrictions apply; Llama-2/CodeLlama "
                   "derived. Comply with the WhiteRabbitNeo Usage Policy.",
        "notice": "Built with Llama. Includes WhiteRabbitNeo offensive/defensive "
                  "security tuning; retain WhiteRabbitNeo's usage terms.",
    },
    {
        "name": "WhiteRabbitNeo-33B-v1 (scale-up)",
        "role": "alternative base model (larger)",
        "source": "https://huggingface.co/WhiteRabbitNeo",
        "license": "Same WhiteRabbitNeo usage terms; larger, needs a bigger GPU.",
        "notice": "Built with Llama. WhiteRabbitNeo 33B.",
    },
    {
        "name": "Qwen3.5-122B (100B preset)",
        "role": "alternative base model (100B+, MoE)",
        "source": "https://huggingface.co/Qwen",
        "license": "See Qwen model card (Apache-2.0 for most Qwen weights); "
                   "verify the exact 122B MoE repo id and license before use.",
        "notice": "Qwen3.5 MoE, ~122B total / ~10B active. QLoRA on rented "
                  "A100/H100 80GB. See RUNBOOK_100B.md.",
    },
    {
        "name": "Nemotron-3-Ultra-550B (500B preset)",
        "role": "alternative base model (500B+, MoE)",
        "source": "https://huggingface.co/nvidia",
        "license": "See NVIDIA Nemotron model card/license; verify the exact repo "
                   "id and terms before use.",
        "notice": "Nemotron 3 Ultra MoE, ~550B total / ~55B active. Cluster scale "
                  "(8x H100 node + DeepSpeed). See RUNBOOK_500B.md.",
    },
    {
        "name": "Foundation-Sec-8B / CyberPal-2.0-20B (alt bases)",
        "role": "alternative bases (defense-leaning)",
        "source": "https://huggingface.co/fdtn-ai/Foundation-Sec-8B",
        "license": "Foundation-Sec: permissive, built on Meta Llama 3.1. "
                   "CyberPal: see model card.",
        "notice": "Built with Llama. Llama 3.1 (c) Meta Platforms, Inc.",
    },
    {
        "name": "gewsefa/pentest-v2",
        "role": "training data (offensive)",
        "source": "https://huggingface.co/gewsefa/pentest-v2",
        "license": "Derived from GTFOBins/HackTricks/HTB/PayloadsAllTheThings -- "
                   "HackTricks is CC-BY-NC (NON-COMMERCIAL). Check before any "
                   "commercial distribution.",
        "notice": "Pentest command dataset; verify upstream source licenses.",
    },
    {
        "name": "WhiteRabbitNeo dataset",
        "role": "training data (offensive+defensive)",
        "source": "https://huggingface.co/WhiteRabbitNeo",
        "license": "See dataset card; WhiteRabbitNeo terms.",
        "notice": "~1.7M red/blue-team instruction pairs.",
    },
    {
        "name": "RedSage datasets (CFW / Seed / Dump)",
        "role": "training data (pretrain + knowledge)",
        "source": "https://huggingface.co/datasets/RISys-Lab/RedSage-CFW",
        "license": "See dataset cards (ICLR 2026 release).",
        "notice": "CyberFineWeb + curated security corpora. NOTE: RedSage-Conv "
                  "is synthetic -- verify its generator before use (provenance).",
    },
    {
        "name": "NYU CTF Bench",
        "role": "training signal + evaluation",
        "source": "https://github.com/NYU-LLM-CTF/NYUCTFBench",
        "license": "See repo (CSAW CTF challenges).",
        "notice": "200 real CTF challenges.",
    },
    {
        "name": "Primus-Seed / AttackQA (alt clean data)",
        "role": "alternative training/eval data",
        "source": "https://huggingface.co/collections/trendmicro-ailab/primus-67b1fd27052b802b4af9d243",
        "license": "Primus: ODC-BY/MIT. AttackQA: see release.",
        "notice": "Clean-provenance defensive corpora and QA.",
    },
]

# Datasets intentionally NOT used in this track, and why (kept for the record so
# the exclusion is a documented decision, not an oversight).
EXCLUDED = [
    ("Primus-Instruct", "responses generated by GPT-4o (distilled from a "
                         "proprietary model); excluded for provenance."),
    ("Primus-Reasoning", "reasoning generated by o1-preview; excluded for provenance."),
    ("Glint-Research/Fable-5-traces", "captured Claude Fable outputs; excluded for "
                                      "provenance (violates upstream terms)."),
]


def render_notice() -> str:
    lines = [
        "Darknode AI -- NOTICE",
        "=" * 60,
        "",
        "Darknode AI is the product identity. The foundation-track model is a",
        "LoRA specialization of an openly-licensed security base model. The",
        "components below are used under their licenses; this NOTICE satisfies",
        "their attribution requirements and must be retained in distributions.",
        "",
        "Components",
        "-" * 60,
    ]
    for c in COMPONENTS:
        lines += [
            f"* {c['name']} -- {c['role']}",
            f"    source:  {c['source']}",
            f"    license: {c['license']}",
            f"    notice:  {c['notice']}",
            "",
        ]
    lines += ["Excluded data (documented provenance decisions)", "-" * 60]
    for name, why in EXCLUDED:
        lines.append(f"* {name}: {why}")
    lines += [
        "",
        "The from-scratch track (darknode_ai.model) is trained from random",
        "initialization by Darknode and carries no upstream model attribution.",
        "",
    ]
    return "\n".join(lines)


def write_notice(path: str | Path = "NOTICE") -> Path:
    p = Path(path)
    p.write_text(render_notice(), encoding="utf-8")
    return p


if __name__ == "__main__":
    print(write_notice())
